<#
.SYNOPSIS
    Generates Install-RdpWrapMonitor.ps1 - a single self-contained deploy script (for RMM upload) that
    embeds Test-RdpWrapStatus.ps1 and Repair-RdpWrapIni.ps1 and registers the scheduled task.

.DESCRIPTION
    Run this after editing either source script so the installer never drifts from them.
    The generated installer, when run as SYSTEM on a target:
      - writes both scripts to C:\ProgramData\RDPWrapMonitor
      - registers task "RDPWrap Monitor" (at startup +2 min, and every 6 h) running the check with -AutoRepair
      - runs the task once and prints the resulting event so the deploy can be verified from RMM output

.PARAMETER OutputPath
    Where to write the installer. Default: Install-RdpWrapMonitor.ps1 beside this script.

.EXAMPLE
    .\Build-Installer.ps1
#>

[CmdletBinding()]
param(
    [string]$OutputPath = (Join-Path $PSScriptRoot 'Install-RdpWrapMonitor.ps1')
)

$ErrorActionPreference = 'Stop'

$check  = (Get-Content (Join-Path $PSScriptRoot 'Test-RdpWrapStatus.ps1') -Raw).TrimEnd()
$repair = (Get-Content (Join-Path $PSScriptRoot 'Repair-RdpWrapIni.ps1')  -Raw).TrimEnd()
foreach ($s in $check, $repair) {
    if ($s -match "(?m)^'@") { throw "Embedded script contains a here-string terminator on its own line; cannot embed" }
}

$installer = @"
<#
.SYNOPSIS
    One-time deploy via RMM "Run Script" (as SYSTEM). Re-running is safe (overwrites scripts, re-registers task).
    GENERATED by Build-Installer.ps1 - edit the source scripts, not this file.

    Installs to C:\ProgramData\RDPWrapMonitor:
      Test-RdpWrapStatus.ps1   health check -> events 1000/1001/1002
      Repair-RdpWrapIni.ps1    adds missing ini section from upstream or rdpwrap-offset-finder.exe -> events 1003/1004/1005
    Registers task "RDPWrap Monitor": boot +2 min and every 6 h, SYSTEM, runs the check with -AutoRepair.
    The repair NEVER restarts TermService on its own; event 1003 is the signal to schedule it.

    rdpwrap-offset-finder.exe is too large to embed - copy it to the install folder separately (RMM file transfer).
    Without it the repair still works whenever upstream sebaxakerhtc/rdpwrap.ini already has the section.
#>

`$ErrorActionPreference = 'Stop'
`$InstallDir = 'C:\ProgramData\RDPWrapMonitor'
`$TaskName   = 'RDPWrap Monitor'

`$CheckScript = @'
$check
'@

`$RepairScript = @'
$repair
'@

New-Item -ItemType Directory -Path `$InstallDir -Force | Out-Null
Set-Content -Path (Join-Path `$InstallDir 'Test-RdpWrapStatus.ps1') -Value `$CheckScript  -Encoding UTF8
Set-Content -Path (Join-Path `$InstallDir 'Repair-RdpWrapIni.ps1')  -Value `$RepairScript -Encoding UTF8

`$exe = Join-Path `$InstallDir 'rdpwrap-offset-finder.exe'
if (Test-Path `$exe) { "Offset finder present: `$exe" } else { "NOTE: `$exe not present - auto-repair limited to upstream ini until it is copied in" }

`$action  = New-ScheduledTaskAction -Execute 'powershell.exe' ``
            -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File ```"`$InstallDir\Test-RdpWrapStatus.ps1```" -AutoRepair"

`$tBoot   = New-ScheduledTaskTrigger -AtStartup
`$tBoot.Delay = 'PT2M'                       # let TermService fully initialise
`$tRepeat = New-ScheduledTaskTrigger -Once -At (Get-Date).Date -RepetitionInterval (New-TimeSpan -Hours 6)

`$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
`$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries ``
              -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 10) -MultipleInstances IgnoreNew

Register-ScheduledTask -TaskName `$TaskName -Action `$action -Trigger @(`$tBoot, `$tRepeat) ``
    -Principal `$principal -Settings `$settings -Force | Out-Null

# Run it immediately and wait for it to finish so the confirmation event is there to read
Start-ScheduledTask -TaskName `$TaskName
`$deadline = (Get-Date).AddMinutes(8)
do { Start-Sleep -Milliseconds 500 } while ((Get-ScheduledTask -TaskName `$TaskName).State -eq 'Running' -and (Get-Date) -lt `$deadline)
Get-WinEvent -FilterHashtable @{LogName='Application'; ProviderName='RDPWrapMonitor'} -MaxEvents 1 |
    Select-Object TimeCreated, Id, LevelDisplayName, @{n='Message';e={`$_.Message.Split("``n")[0]}}
"@

Set-Content -Path $OutputPath -Value $installer -Encoding UTF8

# Verify: parses, and the embedded copies round-trip exactly
$errs = $null; $tok = $null
$ast = [Management.Automation.Language.Parser]::ParseFile($OutputPath, [ref]$tok, [ref]$errs)
if ($errs.Count) { throw "Generated installer has parse errors: $($errs | ForEach-Object Message)" }
$embedded = $ast.FindAll({ $args[0] -is [Management.Automation.Language.StringConstantExpressionAst] -and $args[0].StringConstantType -eq 'SingleQuotedHereString' }, $true)
if ($embedded[0].Value -ne $check -or $embedded[1].Value -ne $repair) { throw "Embedded scripts do not match sources" }

Write-Host "Generated $OutputPath ($((Get-Content $OutputPath).Count) lines) - parse OK, embedded scripts verified"
