<#
.SYNOPSIS
    One-time deploy via RMM "Run Script" (as SYSTEM). Re-running is safe (overwrites scripts, re-registers task).
    GENERATED by Build-Installer.ps1 - edit the source scripts, not this file.

    Installs to C:\ProgramData\RDPWrapMonitor:
      Test-RdpWrapStatus.ps1   health check -> events 1000/1001/1002
      Repair-RdpWrapIni.ps1    adds missing ini section from upstream or rdpwrap-offset-finder.exe -> events 1003/1004/1005
    Registers task "RDPWrap Monitor": boot +2 min and every 6 h, SYSTEM, runs the check with -AutoRepair.
    The repair NEVER restarts TermService on its own; event 1003 is the signal to schedule it.

    rdpwrap-offset-finder.exe is too large to embed - copy it to the install folder separately (RMM file transfer).
    Without it the repair still works whenever upstream sebaxakerhtc/rdpwrap.ini already has the section.
#>

$ErrorActionPreference = 'Stop'
$InstallDir = 'C:\ProgramData\RDPWrapMonitor'
$TaskName   = 'RDPWrap Monitor'

$CheckScript = @'
<#
.SYNOPSIS
    Verifies RDP Wrapper is patched and functional. Logs result to the Application
    event log (source RDPWrapMonitor) so Atera can alert on it.

.DESCRIPTION
    Checks performed:
      1. TermService is running
      2. TermService ServiceDll points at rdpwrap.dll (not the stock termsrv.dll)
      3. rdpwrap.dll is actually loaded inside the TermService svchost process
      4. The installed termsrv.dll version has a matching [x.x.x.x] section in rdpwrap.ini
      5. RDP listener port is in LISTEN state
      6. fSingleSessionPerUser / fDenyTSConnections not set against us

    Event IDs (Application log, source RDPWrapMonitor):
      1000 = Information, all checks passed
      1001 = Error, one or more checks failed (Atera alerts on this)
      1002 = Error, check script itself hit an exception
      1003-1005 are written by Repair-RdpWrapIni.ps1 (see that script)

    Exit code 0 = healthy, 1 = failed. Atera Automation Profiles show non-zero as a failed run.
#>

[CmdletBinding()]
param(
    # Set this if users share a single account and each connection must get its own session.
    # Without it, fSingleSessionPerUser=1 (the Windows default) is reported but not treated as a failure.
    [switch]$RequireMultiSessionPerUser,
    # When the failure is a missing rdpwrap.ini section, run Repair-RdpWrapIni.ps1 (same folder) to add it.
    # Never restarts TermService; the repair script logs 1003 so the restart gets scheduled.
    [switch]$AutoRepair
)

$ErrorActionPreference = 'Stop'
$Source  = 'RDPWrapMonitor'
$LogName = 'Application'

if (-not [System.Diagnostics.EventLog]::SourceExists($Source)) {
    New-EventLog -LogName $LogName -Source $Source
}

$fail = New-Object System.Collections.Generic.List[string]
$info = New-Object System.Collections.Generic.List[string]

try {
    # 1. Service running (allow up to 3 min on a slow boot before calling it a failure)
    $svc = Get-Service TermService
    if ($svc.Status -ne 'Running') {
        try { $svc.WaitForStatus('Running', [TimeSpan]::FromMinutes(3)) } catch {}
        $svc.Refresh()
    }
    if ($svc.Status -ne 'Running') { $fail.Add("TermService status is '$($svc.Status)'") }

    # 2. ServiceDll -> rdpwrap.dll
    $svcDll = (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\TermService\Parameters' -Name ServiceDll).ServiceDll
    $svcDll = [Environment]::ExpandEnvironmentVariables($svcDll)
    $info.Add("ServiceDll = $svcDll")
    if ($svcDll -notmatch 'rdpwrap\.dll$') {
        $fail.Add("ServiceDll is not rdpwrap.dll (RDP Wrapper uninstalled or reverted by Windows Update)")
    }
    elseif (-not (Test-Path $svcDll)) {
        $fail.Add("ServiceDll path does not exist: $svcDll")
    }

    # 3. rdpwrap.dll loaded in the TermService host process
    $pidTS = (Get-CimInstance Win32_Service -Filter "Name='TermService'").ProcessId
    if ($pidTS -gt 0) {
        $loaded = $false
        try {
            $loaded = [bool]((Get-Process -Id $pidTS).Modules | Where-Object { $_.ModuleName -ieq 'rdpwrap.dll' })
        } catch {
            # Modules enumeration can fail for a 64-bit svchost from a 32-bit host; fall back to tasklist
            $loaded = (tasklist /m rdpwrap.dll /fi "PID eq $pidTS" 2>$null) -match 'svchost'
        }
        $info.Add("rdpwrap.dll loaded in PID $pidTS = $loaded")
        if (-not $loaded) { $fail.Add("rdpwrap.dll is not loaded in TermService process (PID $pidTS)") }
    } else {
        $fail.Add("TermService has no running process")
    }

    # 4. termsrv.dll version has a section in rdpwrap.ini
    $termsrv    = Join-Path $env:SystemRoot 'System32\termsrv.dll'
    $termsrvVer = (Get-Item $termsrv).VersionInfo
    $verString  = '{0}.{1}.{2}.{3}' -f $termsrvVer.FileMajorPart, $termsrvVer.FileMinorPart, $termsrvVer.FileBuildPart, $termsrvVer.FilePrivatePart
    $info.Add("termsrv.dll = $verString")

    # Only meaningful when ServiceDll is rdpwrap.dll; otherwise check 2 already reported the real problem
    if ($svcDll -match 'rdpwrap\.dll$') {
        $iniPath = Join-Path (Split-Path $svcDll -Parent) 'rdpwrap.ini'
        if (-not (Test-Path $iniPath)) {
            $fail.Add("rdpwrap.ini not found at $iniPath")
        } else {
            $iniText = Get-Content $iniPath -Raw
            if ($iniText -notmatch "(?m)^\[$([regex]::Escape($verString))\]\s*$") {
                $fail.Add("rdpwrap.ini has no [$verString] section - termsrv.dll was updated and is NOT supported by the current ini")
                $repair = Join-Path $PSScriptRoot 'Repair-RdpWrapIni.ps1'
                if ($AutoRepair -and (Test-Path $repair)) {
                    $repairOut = & $repair 2>&1 | Out-String
                    $info.Add("Auto-repair (exit $LASTEXITCODE):`n" + (($repairOut.Trim() -split "`r?`n" | ForEach-Object { "    $_" }) -join "`n"))
                }
            } else {
                $info.Add("rdpwrap.ini has [$verString] section")
            }
            if ($iniText -match '(?m)^Updated=(.+)$') { $info.Add("rdpwrap.ini Updated=$($Matches[1].Trim())") }
        }
    }

    # 5. Listener port
    $port = 3389
    try { $port = (Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name PortNumber).PortNumber } catch {}
    $listening = Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue
    $info.Add("Port $port listening = $([bool]$listening)")
    if (-not $listening) { $fail.Add("Nothing is listening on TCP $port") }

    # 6. Policy / registry flags that would silently kill multi-session
    $ts = Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server'
    if ($ts.fDenyTSConnections -eq 1)   { $fail.Add("fDenyTSConnections=1 (Remote Desktop disabled)") }
    $polPath = 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services'
    $pol = if (Test-Path $polPath) { Get-ItemProperty $polPath } else { $null }
    if ($pol -and $pol.MaxInstanceCount -eq 1) { $fail.Add("GPO MaxInstanceCount=1 (limits server to one RDP session)") }

    # fSingleSessionPerUser=1 only stops the SAME account holding two sessions; different users are unaffected.
    $singlePerUser = ($ts.fSingleSessionPerUser -eq 1) -or ($pol -and $pol.fSingleSessionPerUser -eq 1)
    $srcNote = if ($pol -and $pol.fSingleSessionPerUser -eq 1) { 'enforced by GPO' } else { 'registry' }
    $info.Add("SingleSessionPerUser = $singlePerUser ($srcNote)")
    if ($RequireMultiSessionPerUser -and $singlePerUser) {
        $fail.Add("fSingleSessionPerUser=1 ($srcNote) but multiple sessions per account are required")
    }

    # Active sessions (informational, helps with post-mortem)
    $sessions = (query session 2>$null | Select-String -Pattern '^\s*(rdp-tcp#\d+)' -AllMatches).Count
    $info.Add("Active RDP sessions = $sessions")
}
catch {
    $msg = "RDPWrapMonitor script exception: $($_.Exception.Message)`n$($_.ScriptStackTrace)"
    Write-EventLog -LogName $LogName -Source $Source -EntryType Error -EventId 1002 -Message $msg
    Write-Output $msg
    exit 1
}

$detail = ($info | ForEach-Object { "  $_" }) -join "`n"

if ($fail.Count -gt 0) {
    $msg = "RDP Wrapper check FAILED on $env:COMPUTERNAME`n`nFailures:`n" + (($fail | ForEach-Object { "  - $_" }) -join "`n") + "`n`nDetails:`n$detail"
    Write-EventLog -LogName $LogName -Source $Source -EntryType Error -EventId 1001 -Message $msg
    Write-Output $msg
    exit 1
}
else {
    $msg = "RDP Wrapper check OK on $env:COMPUTERNAME`n`nDetails:`n$detail"
    Write-EventLog -LogName $LogName -Source $Source -EntryType Information -EventId 1000 -Message $msg
    Write-Output $msg
    exit 0
}
'@

$RepairScript = @'
<#
.SYNOPSIS
    Adds the missing [termsrv version] section to rdpwrap.ini after a Windows Update bumps termsrv.dll.

.DESCRIPTION
    Idempotent. Exits 0 with no changes if the ini already covers the installed termsrv.dll.
    Otherwise finds offsets, in order of preference:
      1. Upstream sebaxakerhtc/rdpwrap.ini (if it already has the section)
      2. rdpwrap-offset-finder.exe (symbol mode, then --nosymbol) in the same folder as this script

    The ini is backed up (rdpwrap.ini.<timestamp>.bak) and the section(s) appended. RDP Wrapper only
    reads the ini at service start, so TermService must be restarted before it takes effect - that is
    NOT done unless -RestartService is passed (it drops every active RDP session).

    Event IDs (Application log, source RDPWrapMonitor):
      1003 = Error, ini patched, TermService restart REQUIRED (Atera alerts so someone schedules it)
      1004 = Error, could not repair (no offsets available / validation failed)
      1005 = Information, ini already current, or restart done and check passed

    Exit codes: 0 = nothing needed / repaired (and restarted if asked), 1 = repair failed, 2 = repaired but restart pending
#>

[CmdletBinding()]
param(
    [switch]$RestartService,        # restart TermService after patching and re-run the health check
    [switch]$DryRun,                # print what would be appended, change nothing
    [switch]$SkipUpstream,          # go straight to the offset finder (testing)
    [string]$IniPath,               # override (default: next to the ServiceDll rdpwrap.dll)
    [string]$TermsrvPath = "$env:SystemRoot\System32\termsrv.dll",
    [string]$OffsetFinderPath = (Join-Path $PSScriptRoot 'rdpwrap-offset-finder.exe'),
    [string]$UpstreamIniUrl = 'https://raw.githubusercontent.com/sebaxakerhtc/rdpwrap.ini/master/rdpwrap.ini'
)

$ErrorActionPreference = 'Stop'
$Source  = 'RDPWrapMonitor'
$LogName = 'Application'

function Write-MonitorEvent([int]$Id, [string]$Type, [string]$Message) {
    try {
        if (-not [System.Diagnostics.EventLog]::SourceExists($Source)) { New-EventLog -LogName $LogName -Source $Source }
        Write-EventLog -LogName $LogName -Source $Source -EntryType $Type -EventId $Id -Message $Message
    } catch { Write-Warning "Could not write event ${Id}: $($_.Exception.Message)" }
    Write-Output $Message
}

# Pull "[ver]" and "[ver-SLInit]" blocks out of ini text. Returns $null if the main section is absent.
function Get-IniSections([string]$Text, [string]$Version) {
    $blocks = @(foreach ($name in @($Version, "$Version-SLInit")) {
        $m = [regex]::Match($Text, "(?ms)^\[$([regex]::Escape($name))\]\s*$.*?(?=^\[|\z)")
        if ($m.Success) { $m.Value.TrimEnd() }
    })
    if (-not $blocks -or $blocks[0] -notmatch "^\[$([regex]::Escape($Version))\]") { return $null }
    return ($blocks -join "`r`n`r`n")
}

function Test-SectionValid([string]$Section, [string]$Version) {
    $required = 'LocalOnlyOffset.x64', 'SingleUserOffset.x64', 'DefPolicyOffset.x64', 'SLInitOffset.x64'
    $missing = $required | Where-Object { $Section -notmatch "(?m)^$([regex]::Escape($_))\s*=\s*[0-9A-Fa-f]+" }
    if ($missing) { throw "Section for $Version is missing keys: $($missing -join ', ')" }
    if ($Section -notmatch "(?m)^\[$([regex]::Escape($Version))-SLInit\]") { throw "Section for $Version has no -SLInit block" }
}

try {
    $v   = (Get-Item $TermsrvPath).VersionInfo
    $ver = '{0}.{1}.{2}.{3}' -f $v.FileMajorPart, $v.FileMinorPart, $v.FileBuildPart, $v.FilePrivatePart

    if (-not $IniPath) {
        $svcDll = [Environment]::ExpandEnvironmentVariables((Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Services\TermService\Parameters' -Name ServiceDll).ServiceDll)
        if ($svcDll -notmatch 'rdpwrap\.dll$') { throw "ServiceDll is '$svcDll', not rdpwrap.dll - RDP Wrapper is not installed; nothing to patch" }
        $IniPath = Join-Path (Split-Path $svcDll -Parent) 'rdpwrap.ini'
    }
    if (-not (Test-Path $IniPath)) { throw "rdpwrap.ini not found at $IniPath" }

    $iniText = Get-Content $IniPath -Raw
    if (Get-IniSections $iniText $ver) {
        Write-MonitorEvent 1005 Information "rdpwrap.ini already has [$ver]; no repair needed ($IniPath)"
        exit 0
    }

    # --- find offsets ---
    $section = $null; $origin = $null
    if (-not $SkipUpstream) {
        try {
            $upstream = (Invoke-WebRequest -Uri $UpstreamIniUrl -UseBasicParsing -TimeoutSec 30).Content
            $section  = Get-IniSections $upstream $ver
            if ($section) { $origin = "upstream ($UpstreamIniUrl)" }
            else { Write-Output "Upstream ini does not have [$ver] yet" }
        } catch { Write-Output "Upstream fetch failed: $($_.Exception.Message)" }
    }

    if (-not $section) {
        if (-not (Test-Path $OffsetFinderPath)) { throw "No upstream section and offset finder not found at $OffsetFinderPath" }
        foreach ($mode in @(@(), @('--nosymbol'))) {
            $out = & $OffsetFinderPath $TermsrvPath @mode 2>&1 | Out-String
            $candidate = Get-IniSections $out $ver
            if ($candidate) {
                try { Test-SectionValid $candidate $ver; $section = $candidate; $origin = "rdpwrap-offset-finder $($mode -join ' ')".Trim(); break }
                catch { Write-Output "Offset finder ($($mode -join ' ')) output rejected: $($_.Exception.Message)" }
            } else {
                Write-Output "Offset finder ($($mode -join ' ')) produced no [$ver] section: $($out.Trim())"
            }
        }
        if (-not $section) { throw "Could not obtain offsets for termsrv.dll $ver from upstream or offset finder" }
    }
    Test-SectionValid $section $ver

    if ($DryRun) {
        Write-Output "DRY RUN - would append to ${IniPath} (source: $origin):`n`n$section"
        exit 0
    }

    # --- apply ---
    $backup = "$IniPath.$(Get-Date -Format 'yyyyMMdd-HHmmss').bak"
    Copy-Item $IniPath $backup
    $sep = if ($iniText.EndsWith("`n")) { "`r`n" } else { "`r`n`r`n" }
    [IO.File]::AppendAllText($IniPath, "$sep$section`r`n", [Text.Encoding]::ASCII)

    if (-not (Get-IniSections (Get-Content $IniPath -Raw) $ver)) { throw "Appended section but re-read of $IniPath does not contain [$ver]" }

    $summary = "rdpwrap.ini patched for termsrv.dll $ver on $env:COMPUTERNAME`nSource : $origin`nBackup : $backup`n`n$section"

    if (-not $RestartService) {
        Write-MonitorEvent 1003 Error "$summary`n`nTermService restart REQUIRED for this to take effect - run outside business hours:`n  Repair-RdpWrapIni.ps1 -RestartService   (or Restart-Service TermService -Force)"
        exit 2
    }

    Write-Output "Restarting TermService..."
    Restart-Service TermService -Force
    Start-Sleep -Seconds 10
    $check = Join-Path $PSScriptRoot 'Test-RdpWrapStatus.ps1'
    $checkOut = if (Test-Path $check) { & $check 2>&1 | Out-String } else { "(Test-RdpWrapStatus.ps1 not found beside this script; check skipped)" }
    if ($LASTEXITCODE -eq 0) {
        Write-MonitorEvent 1005 Information "$summary`n`nTermService restarted; post-restart check:`n$checkOut"
        exit 0
    } else {
        Write-MonitorEvent 1004 Error "$summary`n`nTermService restarted but post-restart check FAILED:`n$checkOut"
        exit 1
    }
}
catch {
    Write-MonitorEvent 1004 Error "RDP Wrapper auto-repair FAILED on $env:COMPUTERNAME`n$($_.Exception.Message)`n$($_.ScriptStackTrace)"
    exit 1
}
'@

New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
Set-Content -Path (Join-Path $InstallDir 'Test-RdpWrapStatus.ps1') -Value $CheckScript  -Encoding UTF8
Set-Content -Path (Join-Path $InstallDir 'Repair-RdpWrapIni.ps1')  -Value $RepairScript -Encoding UTF8

$exe = Join-Path $InstallDir 'rdpwrap-offset-finder.exe'
if (Test-Path $exe) { "Offset finder present: $exe" } else { "NOTE: $exe not present - auto-repair limited to upstream ini until it is copied in" }

$action  = New-ScheduledTaskAction -Execute 'powershell.exe' `
            -Argument "-NoProfile -NonInteractive -ExecutionPolicy Bypass -File `"$InstallDir\Test-RdpWrapStatus.ps1`" -AutoRepair"

$tBoot   = New-ScheduledTaskTrigger -AtStartup
$tBoot.Delay = 'PT2M'                       # let TermService fully initialise
$tRepeat = New-ScheduledTaskTrigger -Once -At (Get-Date).Date -RepetitionInterval (New-TimeSpan -Hours 6)

$principal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -LogonType ServiceAccount -RunLevel Highest
$settings  = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
              -StartWhenAvailable -ExecutionTimeLimit (New-TimeSpan -Minutes 10) -MultipleInstances IgnoreNew

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($tBoot, $tRepeat) `
    -Principal $principal -Settings $settings -Force | Out-Null

# Run it immediately and wait for it to finish so the confirmation event is there to read
Start-ScheduledTask -TaskName $TaskName
$deadline = (Get-Date).AddMinutes(8)
do { Start-Sleep -Milliseconds 500 } while ((Get-ScheduledTask -TaskName $TaskName).State -eq 'Running' -and (Get-Date) -lt $deadline)
Get-WinEvent -FilterHashtable @{LogName='Application'; ProviderName='RDPWrapMonitor'} -MaxEvents 1 |
    Select-Object TimeCreated, Id, LevelDisplayName, @{n='Message';e={$_.Message.Split("`n")[0]}}
